spring:
  profiles:
    active: prod
    default: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  config:
    import:
      - classpath:private/private-config.yml
      - classpath:private/db-config.yml
